# Generated by Django 6.0.1 on 2026-01-25 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning_logs", "0004_publicentry_publictopic"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="publictopic",
            name="owner",
        ),
        migrations.AlterField(
            model_name="publicentry",
            name="topic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="learning_logs.publictopic",
            ),
        ),
    ]
